In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]

type(data1)

list

In [5]:
data1

[6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data1)

type(arr1)

numpy.ndarray

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
data2 = [[1,2,3,4], [5,6,7,8]]

arr2 = np.array(data2)

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.dtype

dtype('int64')

In [11]:
data_ill_formed = [[1,2,3], [5,6,7,8]]

arr3 = np.array(data_ill_formed)

In [12]:
arr3

array([[1, 2, 3], [5, 6, 7, 8]], dtype=object)

In [13]:
arr3.dtype

dtype('O')

배열과 스칼라 연산

In [17]:
# 오류!
arr = np.array([1., 2., 3.], [4.,5.,6.]) 

TypeError: data type not understood

In [15]:
arr = np.array([[1., 2., 3.], [4.,5.,6.]])

In [16]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [18]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [19]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [22]:
2**10

1024

In [21]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [23]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [24]:
np.array([1,2]) + np.array([3,4])

array([4, 6])

In [25]:
[1,2]*10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [27]:
np.array([1,2])*10

array([10, 20])

In [26]:
[1,2]/10

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [29]:
np.array([1.,2.])/10

array([ 0.1,  0.2])

색인과 슬라이싱

In [32]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5] # 인덱싱

5

In [34]:
arr[5:8] # 슬라이싱

array([5, 6, 7])

In [35]:
alist = range(10)
alist[5:8] = 12

TypeError: can only assign an iterable

In [37]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
# 파이썬 리스트
list_slice = alist[5:8]
list_slice

[5, 6, 7]

In [41]:
# 슬라이스는 독립적
list_slice[1] = 12345
alist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
# ndarray
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [39]:
# ndarray의 슬라이스는 복사본이 아님!
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [42]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
arr2d[2]

array([7, 8, 9])

In [44]:
arr2d[0][2]

3

In [45]:
arr2d[0,2] # 다차원 인덱싱

3

In [46]:
arr3d = np.array([[[1,2,3], [4,5,6]], 
                  [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
old_values = arr3d[0].copy()

In [50]:
arr3d[0] = 42 # 스칼라 값을 브로드캐스팅
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[1,0]

array([7, 8, 9])

슬라이스 색인

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[1, :2]

array([4, 5])

In [58]:
arr2d[2, :1]

array([7])

In [59]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [60]:
arr2d[:, 0]

array([1, 4, 7])

예제: 계단 오르내리기

In [63]:
for n in range(10):
    print(random.randint(0,1))

1
1
0
1
1
1
0
0
0
1


In [65]:
import random # 난수 생성을 위한 표준 모듈
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
    
print(walk[:10])

[0, -1, -2, -3, -2, -3, -2, -3, -2, -1]


In [70]:
nsteps = 1000
draws = np.random.randint(0,2, size=nsteps)
steps = np.where(draws > 0 , 1, -1)
walk = steps.cumsum()

print(walk[:10])

[-1  0  1  0 -1  0 -1 -2 -3 -4]


In [71]:
walk.min()

-11

In [72]:
walk.max()

35

In [74]:
(np.abs(walk) >= 10).argmax()

117

5000번 시뮬레이션

In [76]:
nwalks = 5000
nsteps = 1000
# 0 또는 1
# 5000 x 1000 행렬
draws = np.random.randint(0,2, size=(nwalks, nsteps))
draws

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 0],
       ..., 
       [0, 1, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 0, 0]])

In [78]:
# draw 행렬에서, 값이 0보다 크면 1, 아니면 -1
steps = np.where(draws > 0, 1, -1)
steps

array([[ 1,  1,  1, ..., -1, -1, -1],
       [ 1,  1,  1, ..., -1, -1,  1],
       [-1,  1,  1, ...,  1, -1, -1],
       ..., 
       [-1,  1,  1, ...,  1,  1, -1],
       [-1, -1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1, -1, -1]])

In [79]:
np.where?

In [80]:
steps.cumsum?

In [84]:
steps.cumsum().shape

(5000000,)

In [85]:
steps.cumsum(1).shape

(5000, 1000)

In [88]:
walks = steps.cumsum(1) # 누적합계는 애써 만들지 말고, 가져다 쓰자

In [89]:
walks.max()

127

In [90]:
walks.min()

-143

In [91]:
hits30 = (np.abs(walks) >= 30).any(1)

In [92]:
hits30

array([ True,  True,  True, ..., False,  True,  True], dtype=bool)

In [93]:
np.random.randint?

In [94]:
random.randint?