# Pandas

## Series

In [17]:
from pandas import Series, DataFrame
import pandas as pd

import numpy as np

In [4]:
obj = Series([4,7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
type(obj.values)

numpy.ndarray

In [7]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [8]:
obj2 = Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2['d']

6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio':35000,
         'Texas': 71000,
        'Oregon': 16000,
        'Utah': 5000}

obj3 = Series(sdata)

In [27]:
sdata # 파이썬 사전은 입력 순서가 보존되지 않는다.

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [22]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = Series(sdata, index=states)

In [26]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [28]:
obj4.values

array([    nan,  35000.,  16000.,  71000.])

In [29]:
type(obj4.values)

numpy.ndarray

In [30]:
obj4.values.dtype

dtype('float64')

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [36]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [37]:
obj3+obj4

California       NaN
Ohio           70000
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64

In [38]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California      NaN
Ohio          35000
Oregon        16000
Texas         71000
Name: population, dtype: float64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

In [41]:
# 파이썬 사전(dict)
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [42]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [43]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [44]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [45]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [49]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [48]:
type(frame2['state'])

pandas.core.series.Series

In [51]:
frame2['three'] # 오류!

KeyError: 'three'

In [50]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [54]:
np.arange(5.)

array([ 0.,  1.,  2.,  3.,  4.])

In [55]:
frame2['debt'] = np.arange(5.)

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [57]:
frame2['debt'] = range(5)

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [59]:
val = Series([-1.2, -1.5, -1.7],
            index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [62]:
del frame2['eastern']

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [64]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002:3.6}}

frame3 = DataFrame(pop)

In [65]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [67]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [66]:
frame3.T # 행열 전환

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [75]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3.T

year    2000  2001  2002
state                   
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [76]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64')

In [77]:
frame3.T.index

Index([u'Nevada', u'Ohio'], dtype='object')

### 핵심 기능

In [83]:
obj = Series([4.5, 7.2, -5.3, 3.6],
            index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [85]:
# 재색인
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [86]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [87]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [88]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: float64

In [89]:
new_obj = obj.drop('c')

In [90]:
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [91]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
data = DataFrame(np.arange(16).reshape(4,4),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data.drop('two')

ValueError: labels ['two'] not contained in axis

In [102]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [103]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [104]:
obj = Series(np.arange(4.),
            index=['a', 'b', 'c', 'd'])

In [105]:
obj['b']

1.0

In [106]:
obj

a    0
b    1
c    2
d    3
dtype: float64

In [107]:
obj[2:4]

c    2
d    3
dtype: float64

In [108]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: float64

In [109]:
obj['b', 'a', 'd'] # 오류!

KeyError: ('b', 'a', 'd')

In [110]:
obj

a    0
b    1
c    2
d    3
dtype: float64

In [111]:
obj[[1,3]]

b    1
d    3
dtype: float64

In [113]:
obj[obj<2] # 필터링: 각 항목의 값을 평가해서 선택

a    0
b    1
dtype: float64

In [114]:
obj['b':'c']

b    1
c    2
dtype: float64

In [115]:
obj['b':'c']=5 # 브로드캐스팅

In [116]:
obj

a    0
b    5
c    5
d    3
dtype: float64

In [117]:
data = DataFrame(np.arange(16).reshape(4,4),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [119]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [120]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [121]:
# 필터링
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# 데이터 준비

In [123]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a','a','b'],
                'data1':range(7)})
df2 = DataFrame({'key': ['a','b','d'],
               'data2': range(3)})

In [124]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [125]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [126]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [127]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [129]:
df3 = DataFrame({'lkey':['b', 'b', 'a', 'c', 'a','a','b'], 
                 'data1': range(7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'],
                'data2': range(3)})

In [130]:
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [131]:
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [132]:
pd.merge(df3,df4)

MergeError: No common columns to perform merge on

In [133]:
# 관계형 데이터베이스 JOIN 작업 참조
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [136]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
          index=['f','e','d','c','b','a'])
b = Series(np.arange(len(a), dtype=np.float64),
          index=['f', 'e', 'd', 'c', 'b', 'a'])

In [137]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [138]:
b

f    0
e    1
d    2
c    3
b    4
a    5
dtype: float64

In [139]:
pd.merge(a,b)

AttributeError: 'Series' object has no attribute 'columns'

In [140]:
b[-1] = np.nan

In [141]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [142]:
b

f     0
e     1
d     2
c     3
b     4
a   NaN
dtype: float64

In [143]:
np.where(pd.isnull(a), b, a) # 꽤 어려움 ...

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [144]:
b[:-2].combine_first(a[2:]) # 위의 연산 기능 제공.,

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [145]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64